
export const FORM_RESET = 'redux-form/RESET';

export const GIPHY_SEARCH_PENDING = 'App/GIPHY_SEARCH_PENDING';
export const GIPHY_SEARCH_SUCCESS = 'App/GIPHY_SEARCH_SUCCESS';
export const GIPHY_SEARCH_ERROR = 'App/GIPHY_SEARCH_ERROR';

export const SIDEBAR_OPEN = 'App/SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'App/SIDEBAR_CLOSE';

export const GIPHY_DETAILS_PENDING = 'App/GIPHY_DETAILS_PENDING';
export const GIPHY_DETAILS_SUCCESS = 'App/GIPHY_DETAILS_SUCCESS';
export const GIPHY_DETAILS_ERROR = 'App/GIPHY_DETAILS_ERROR';
