export const INCREMENT_COUNTER = 'App/INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'App/DECREMENT_COUNTER';

export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';
export const FORM_RESET = 'redux-form/RESET';

export const GIPHY_SEARCH_PENDING = 'App/GIPHY_SEARCH_PENDING';
export const GIPHY_SEARCH_SUCCESS = 'App/GIPHY_SEARCH_SUCCESS';
export const GIPHY_SEARCH_ERROR = 'App/GIPHY_SEARCH_ERROR';

export const SELECT_GIF = 'App/SELECT_GIF';

export const GIPHY_DETAILS_PENDING = 'App/GIPHY_DETAILS_PENDING';
export const GIPHY_DETAILS_SUCCESS = 'App/GIPHY_DETAILS_SUCCESS';
export const GIPHY_DETAILS_ERROR = 'App/GIPHY_DETAILS_ERROR';
